---

- name: "Create nginx network"
  docker_network:
    name: frontend

- name: "Create database network"
  docker_network:
    name: backend

- name: "Database for ctfd"
  docker_container:
    name: mariadb
    image: mariadb
    networks:
      - name: "backend"
    env:
        MYSQL_ROOT_PASSWORD: "ctfd"
        MYSQL_USER: "ctfd"
        MYSQL_PASSWORD: "ctfd"
        MYSQL_DATABASE: "ctfd"

- name: "Container ctfd"
  docker_container:
    name: ctfd
    image: ctfd/ctfd
    ports:
      - "8000:8000"
    volumes:
        - /opt/ctfd/logs:/var/log/CTFd
        - /opt/ctfd/uploads:/var/uploads
    env:
       UPLOAD_FOLDER: "/var/uploads"
       DATABASE_URL: "mysql+pymysql://ctfd:ctfd@mariadb/ctfd"
       WORKERS: "1"
       LOG_FOLDER: "/var/log/CTFd"
       ACCESS_LOG: "-"
       ERROR_LOG: "-"
       REVERSE_PROXY: "true"
    networks:
      - name: frontend
      - name: backend

- name: "Download and create nginx container"
  docker_container:
    name: nginx
    image: nginx
    networks:
      - name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx/sites:/etc/nginx/conf.d

